name: CI/CD Frontend - HOTELSOFT

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install --legacy-peer-deps

      - name: Compilar Angular
        run: npm run build --prod

      - name: Construir imagen Docker del frontend
        run: docker build -t hotelsoft-frontend .

      - name: Subir imagen a DockerHub
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker tag hotelsoft-frontend $DOCKER_USER/hotelsoft-frontend:latest
          docker push $DOCKER_USER/hotelsoft-frontend:latest

      - name: Desplegar localmente con Docker
        run: |
          docker stop hotelsoft-frontend || true
          docker rm hotelsoft-frontend || true
          docker run -d -p 4200:80 --name hotelsoft-frontend hotelsoft-frontend
